= CR des sessions

== 23/09/2021

Discussion autour de la taille des aggregats: Jeu est il trop gros? On pourra en discuter en repartant de l'Event Storming, mais on veut allez au bout de l'implem actuel.
On ajoute un test pour montrer qu'on ne peut pas tirer une carte déja tiré et on supprime l'injection de fun dans l'aggregat.

Idée pour la prochaine fois:

- Ajouter la partie infra qui gère le deck et la possibilité de tirer une cartre au hasard dans un paquet de carte?
- ajouter l'évènement CardPicked pour garantir qu'on ne peut pas construire une game invalide.


== 14/10/2021

Il manque l'ajout de la carte prise lors du StartNewTurn
Est-il possible de merge StartNewTurn et EndTurn ? Quid de StartNewTurn si c'est utilisé une seule fois

* Ajouter la partie infra qui gère le deck et la possibilité de tirer une cartre au hasard dans un paquet de carte? *


== 21/10/2021

Règles pas encore implémentées : 
- perte de vie du joueur adverse quand on joue une carte qui provoque la fin de partie quand l'adversaire n'a plus de vie