= CR des sessions

== 23/09/2021

Discussion autour de la taille des aggregats: Jeu est il trop gros? On pourra en discuter en repartant de l'Event Storming, mais on veut allez au bout de l'implem actuel.
On ajoute un test pour montrer qu'on ne peut pas tirer une carte déja tiré et on supprime l'injection de fun dans l'aggregat.

Idée pour la prochaine fois:

- Ajouter la partie infra qui gère le deck et la possibilité de tirer une cartre au hasard dans un paquet de carte?
- ajouter l'évènement CardPicked pour garantir qu'on ne peut pas construire une game invalide.


== 14/10/2021

Il manque l'ajout de la carte prise lors du StartNewTurn
Est-il possible de merge StartNewTurn et EndTurn ? Quid de StartNewTurn si c'est utilisé une seule fois

* Ajouter la partie infra qui gère le deck et la possibilité de tirer une cartre au hasard dans un paquet de carte? *


== 21/10/2021

Refactor du code: 
- le deck est randomisé à l'initialisation du jeu
- suppression des valeurs "random" injectées dans les commandes 


== 28/10/2021

DONE :
- perte de vie du joueur adverse quand on joue une carte qui provoque la fin de partie quand l'adversaire n'a plus de vie
- refactor code des commandes & ajout de méthodes d'extensions sur GameState  


== 04/11/2021

DONE :
- GameState : supprimer le optional du CurrentPlayer


== 08/11/2021

DONE :
- hydrate : supprimer les "match Player1 Player2"
- Refactor du code d'exécution des commandes


== TODO : 
- Refactor des tests : factory methods pour créer de l'historique pour les commandes  
- vérifier que le deck est complet (20 cartes) au démarrage (cf: CreateGame)
- vérifier qu'on ne peut plus piocher de carte si le deck est vide (écrire un test)
    -> aussi règle du "bleeding out"
- vérifier qu'on ajoute à la main la carte que l'on retire du deck
- vérifier que l'on ne peut pas dépasser le max mana de 10
